# Generated by Django 5.0.4 on 2024-05-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_otp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lunch',
            unique_together={('user', 'date')},
        ),
    ]
