# Generated by Django 5.0.4 on 2024-06-11 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0003_alter_lunch_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterModelOptions(
            name='lunch',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.AlterUniqueTogether(
            name='lunch',
            unique_together=set(),
        ),
    ]
