# Generated by Django 5.0.4 on 2024-10-08 15:23

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthdate',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='آخرین مدرک تحصیلی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='end_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ پایان کار'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نام پدر'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_file',
            field=models.BooleanField(default=False, verbose_name='کاربر فایلی است؟'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='major',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='start_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ شروع به کار'),
        ),
    ]
