# Generated by Django 5.0.4 on 2024-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0006_customuser_address_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='تصویر پروفایل'),
        ),
    ]
