# Generated by Django 5.0.4 on 2024-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0007_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='salary',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='حقوق ساعتی'),
        ),
    ]
