# Generated by Django 5.0.4 on 2024-10-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0008_customuser_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='salary',
            field=models.PositiveIntegerField(default=0, verbose_name='حقوق ساعتی'),
        ),
    ]
