# Generated by Django 5.0.4 on 2024-12-07 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0009_alter_customuser_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(blank=True, choices=[('man', 'مرد'), ('woman', 'زن')], max_length=10, null=True, verbose_name='جنسیت'),
        ),
    ]
