# Generated by Django 5.0.4 on 2025-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0010_customuser_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rfid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد RFID'),
        ),
    ]
