# Generated by Django 5.0.4 on 2025-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0011_customuser_rfid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='سمت'),
        ),
    ]
