# Generated by Django 5.0.4 on 2026-10-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0012_customuser_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lunch',
            unique_together={('user', 'date')},
        ),
    ]
