# Generated by Django 5.0.4 on 2024-10-08 17:37

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_sharedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
