# Generated by Django 5.0.4 on 2024-10-15 11:32

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_alter_sharedfile_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.FileField(upload_to='shared_files/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='recipients',
            field=models.ManyToManyField(related_name='received_files', to=settings.AUTH_USER_MODEL, verbose_name='گیرندگان'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_files', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
    ]
