# Generated by Django 5.0.4 on 2024-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_alter_sharedfile_created_at_alter_sharedfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='seen',
            field=models.BooleanField(default=False, verbose_name='خوانده شده؟'),
        ),
    ]
