# Generated by Django 5.0.4 on 2024-07-13 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_season_seasonsurveyquestion_seasonsurveyresponse'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyreport',
            options={'verbose_name': 'گزارش ماهانه', 'verbose_name_plural': 'گزارش های ماهانه'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'فصل', 'verbose_name_plural': 'فصل ها'},
        ),
        migrations.AlterModelOptions(
            name='seasonsurveyquestion',
            options={'verbose_name': 'سوال نظرسنجی', 'verbose_name_plural': 'سوال های نظرسنجی'},
        ),
        migrations.AlterModelOptions(
            name='seasonsurveyresponse',
            options={'verbose_name': 'پاسخ نظرسنجی', 'verbose_name_plural': 'پاسخ های نظرسنجی'},
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('file', models.FileField(upload_to='payslips/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
