# Generated by Django 5.0.4 on 2024-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0005_alter_payslip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='file',
            field=models.FileField(upload_to='payslips/'),
        ),
    ]
