# Generated by Django 5.0.4 on 2024-07-13 10:28

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_alter_payslip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='date',
            field=django_jalali.db.models.jDateField(),
        ),
    ]
