# Generated by Django 5.0.4 on 2024-11-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_alter_payslip_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.IntegerField(choices=[(1, 'Farvardin'), (2, 'Ordibehesht'), (3, 'Khordad'), (4, 'Tir'), (5, 'Mordad'), (6, 'Shahrivar'), (7, 'Mehr'), (8, 'Aban'), (9, 'Azar'), (10, 'Dey'), (11, 'Bahman'), (12, 'Esfand')]),
        ),
    ]
