# Generated by Django 5.0.4 on 2024-12-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_alter_monthlyreport_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='month',
            field=models.IntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')]),
        ),
    ]
