# Generated by Django 5.0.4 on 2024-07-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_alter_monthlyreport_options_alter_season_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payslip',
            name='file',
            field=models.FileField(upload_to='media/payslips/'),
        ),
    ]
