# Generated by Django 5.0.4 on 2024-07-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_alter_payslip_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payslip',
            options={'verbose_name': 'فیش حقوقی', 'verbose_name_plural': 'فیش حقوقی'},
        ),
    ]
