# Generated by Django 5.0.4 on 2024-10-19 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendacerecord_is_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='attendance.attendacerecord'),
        ),
    ]
