# Generated by Django 5.0.4 on 2024-10-19 13:35

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendancerequest_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendacerecord',
            name='is_finalized',
        ),
        migrations.AlterField(
            model_name='attendancerequest',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
