# Generated by Django 5.0.4 on 2024-10-29 07:38

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_remove_attendacerecord_is_finalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacerecord',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2024, 10, 29)),
        ),
    ]
