# Generated by Django 5.0.4 on 2025-05-26 12:11

import datetime
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_alter_attendacerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacerecord',
            name='date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2025, 5, 26)),
        ),
    ]
