# Generated by Django 5.0.4 on 2026-10-04 12:41

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_attendacerecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendacerecord',
            name='date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today),
        ),
    ]
